[dev]
framework = "#static"
command = "npx @11ty/eleventy --quiet --watch"
publish = "_site"

[[edge_functions]]
function = "basic-auth"
path = "/*"

[[edge_functions]]
function = "abtesting"
path = "/*"

[[edge_functions]]
function = "eleventy-edge"
path = "/*"
